### ISSUE TITLE
Generic personalization plugin not working in ripe-retail

### ISSUE THREAD

**Issue by BeeMargarida** [ripe-tech/ripe-commons-pluginus#126]
## Description

The generic personalization plugin in `ripe-retail` is not showing the dropdowns and inputs that allow the personalization. The cause might be due to these components not existing both in `ripe-retail` nor in `ripe-commons-pluginus`.  

## Expected vs. Observed

| - | - |
| --- | --- |
| **Expected** | Similar to ripe-white, dropdowns and inputs appear that allow the user to choose properties and the initials. |
| **Observed** | No dropdowns nor inputs appear. |

## Repro Steps

1. Log on ripe-retail
2. Create new store with brand `Ermenegildo Zegna` and default product equal to:
`query:brand=ermenegildo_zegna&model=my_tiziano&version=50&p=band1:calf_leather_ez:white&p=band2:calf_leather_ez:white&p=band3:calf_leather_ez:white&p=laces:nylon_ez:lac33_white&p=lining:calf_lining_ez:vicuna&p=shadow:default:default&p=sole:rubber_ez:white&p=spoiler:calf_leather_ez:white&p=toe:calf_leather_ez:white&p=tongue:calf_leather_ez:white`
2. Open the newly created store
3. Open the personalization

## Environment

| Key | Value |
| --- | --- |
| **Device** | MacBook Pro |
| **Operating System** | Mac OS X |
| **Browser** | Firefox |
| **Instance (URL)** | http://localhost:8080/ |

## Screens

<img width="1650" alt="Screenshot 2020-06-18 at 13 58 20" src="https://user-images.githubusercontent.com/25725586/85022892-d3b9af00-b16b-11ea-91c0-a6920ffe23b2.png">
<img width="1649" alt="Screenshot 2020-06-18 at 14 18 37" src="https://user-images.githubusercontent.com/25725586/85024920-a3274480-b16e-11ea-9fa2-5db7469bd372.png">

**Comment by joamag** [comment]
@gcandal Let's to address this issue. Although ripe-retail is legacy having this issue fixed ensures the implementation of the plugin architecture philosophy.

**Comment by gcandal** [comment]
@BeeMargarida let's port the missing component to ripe-retail.

**Comment by joamag** [comment]
@gcandal we should respect the layout and visuals of ripe retail

**Comment by dsafonso** [comment]
test OK
![image](https://user-images.githubusercontent.com/24550956/87033861-e3fb0200-c1de-11ea-9196-54b95bfd4836.png)
![image](https://user-images.githubusercontent.com/24550956/87034029-1ad11800-c1df-11ea-8b16-ddf206230d54.png)

**Comment by gcandal** [comment]
@dsafonso don't forget closing 🎖️

**Comment by dsafonso** [comment]
@gcandal I don't closed because is missing the test script
